apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  serviceAccountName: demo-user
  containers:
  -  name: app
     image: busybox
     command: ["sh","-c","echo Secure Pod Running; sleep 3600"]
     