apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: demo-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:default:demo-user
  